In [1]:
# Setting all warnings off
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import sys
import re

In [3]:
characters = "abcdefghijklmnopqrstuvwxyz0123456789-,;.!?:'\"/\\|_@#$%^&*~`+ =<>()[]{}"
characters_2 = "abcdefghijklmnopqrstuvwxyz@# "
url_chars = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"

In [4]:
def lower_case(tweet_data):
    for i, tweet in enumerate(tweet_data):
        tweet_data.iloc[i] = tweet.lower()
    return tweet_data

In [5]:
def character_clean(tweet_data):
    for i, tweet in enumerate(tweet_data):
        sentence = ''
        for char in tweet:
            if char in characters_2:
                sentence += char
        tweet_data.iloc[i] = sentence
    return tweet_data

In [6]:
def remove_hastag(tweet_data):
    for i, tweet in enumerate(tweet_data):
        ignore = 0
        sentence = ''
        for char in tweet:
            if char == '#':
                ignore = 1
            if ignore == 1 and char == ' ':
                ignore = 0
            if ignore == 0:
                sentence += char
        tweet_data.iloc[i] = sentence
    return tweet_data

In [7]:
def remove_userid(tweet_data):
    for i, tweet in enumerate(tweet_data):
        ignore = 0
        sentence = ''
        for char in tweet:
            if char == '@':
                ignore = 1
            if ignore == 1 and char == ' ':
                ignore = 0
            if ignore == 0:
                sentence += char
        tweet_data.iloc[i] = sentence
    return tweet_data

In [8]:
def remove_url(tweet_data):
    for i, tweet in enumerate(tweet_data):
        url = re.findall(url_chars, tweet)
        to_remove = [x[0] for x in url]
        for _url in to_remove:
            tweet = tweet.replace(_url, '')
        sentence = tweet
        tweet_data.iloc[i] = sentence
    return tweet_data

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [10]:
file = "/content/drive/MyDrive/Tweet/training.csv"

In [11]:
import chardet
with open(file, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [12]:
colnames = ["target","ids","date","flag","user","text"]

train_data = pd.read_csv(file,encoding='ISO-8859-1',names=colnames, header=None)

In [13]:

train_data['target'].unique()

array([0, 4])

In [14]:
train_data['target'].value_counts()

0    800000
4    800000
Name: target, dtype: int64

In [15]:
train_data_tweet = train_data['text'].sample(frac = 0.10, random_state = 101)
train_data_tweet

250977    @Kardboard yea  ugh. I don't wanna move either...
150064    Guess there's a first time for everything, my ...
710275    My cousin is going to America and it's NOT FAI...
367641    @mitchelmusso Ahh this is my first comment to ...
575674    taking care of my good friend jessica she is s...
                                ...                        
110202    NOT ONLY AM I UP AND CANT SLEEP, I JUST WATCHE...
777860    Upset that j1s have taken over my cosy spot in...
268962    I'm wondering what to wear today...  I sure wi...
983370    @EmoPartyGirl yeh whistlers cool u ever see cr...
796007                                Its storm'n ova here 
Name: text, Length: 160000, dtype: object

## Preprocessing

In [16]:
train_data_tweet = lower_case(train_data_tweet)
train_data_tweet

250977    @kardboard yea  ugh. i don't wanna move either...
150064    guess there's a first time for everything, my ...
710275    my cousin is going to america and it's not fai...
367641    @mitchelmusso ahh this is my first comment to ...
575674    taking care of my good friend jessica she is s...
                                ...                        
110202    not only am i up and cant sleep, i just watche...
777860    upset that j1s have taken over my cosy spot in...
268962    i'm wondering what to wear today...  i sure wi...
983370    @emopartygirl yeh whistlers cool u ever see cr...
796007                                its storm'n ova here 
Name: text, Length: 160000, dtype: object

In [17]:
train_data_tweet = remove_url(train_data_tweet)
train_data_tweet

250977    @kardboard yea  ugh. i don't wanna move either...
150064    guess there's a first time for everything, my ...
710275    my cousin is going to america and it's not fai...
367641    @mitchelmusso ahh this is my first comment to ...
575674    taking care of my good friend jessica she is s...
                                ...                        
110202    not only am i up and cant sleep, i just watche...
777860    upset that j1s have taken over my cosy spot in...
268962    i'm wondering what to wear today...  i sure wi...
983370    @emopartygirl yeh whistlers cool u ever see cr...
796007                                its storm'n ova here 
Name: text, Length: 160000, dtype: object

In [18]:
train_data_tweet = remove_userid(train_data_tweet)
train_data_tweet

250977     yea  ugh. i don't wanna move either because a...
150064    guess there's a first time for everything, my ...
710275    my cousin is going to america and it's not fai...
367641     ahh this is my first comment to youu!! love i...
575674    taking care of my good friend jessica she is s...
                                ...                        
110202    not only am i up and cant sleep, i just watche...
777860    upset that j1s have taken over my cosy spot in...
268962    i'm wondering what to wear today...  i sure wi...
983370       yeh whistlers cool u ever see crankworks comp 
796007                                its storm'n ova here 
Name: text, Length: 160000, dtype: object

In [19]:
#train_data_tweet = remove_hastag(train_data_tweet)
train_data_tweet

250977     yea  ugh. i don't wanna move either because a...
150064    guess there's a first time for everything, my ...
710275    my cousin is going to america and it's not fai...
367641     ahh this is my first comment to youu!! love i...
575674    taking care of my good friend jessica she is s...
                                ...                        
110202    not only am i up and cant sleep, i just watche...
777860    upset that j1s have taken over my cosy spot in...
268962    i'm wondering what to wear today...  i sure wi...
983370       yeh whistlers cool u ever see crankworks comp 
796007                                its storm'n ova here 
Name: text, Length: 160000, dtype: object

In [20]:
train_data_tweet = character_clean(train_data_tweet)
train_data_tweet

250977     yea  ugh i dont wanna move either because all...
150064    guess theres a first time for everything my ca...
710275    my cousin is going to america and its not fair...
367641     ahh this is my first comment to youu love it ...
575674    taking care of my good friend jessica she is s...
                                ...                        
110202    not only am i up and cant sleep i just watched...
777860    upset that js have taken over my cosy spot in ...
268962    im wondering what to wear today  i sure wish i...
983370       yeh whistlers cool u ever see crankworks comp 
796007                                 its stormn ova here 
Name: text, Length: 160000, dtype: object

## Feature Extraction

In [21]:

import nltk
nltk.download('words')
words = set(nltk.corpus.words.words())

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


In [22]:
def remove_nonEng(tweet_data):
    for i, tweet in enumerate(tweet_data):
        sentence = " ".join(w for w in nltk.wordpunct_tokenize(tweet) if w.lower() in words or not w.isalpha())
        tweet_data.iloc[i] = sentence
    return tweet_data

In [23]:
# train_data_tweet = remove_nonEng(train_data_tweet)
# train_data_tweet

In [24]:
import tensorflow as tf
import numpy as np

In [25]:
# convert string to lower case 
train_texts = train_data_tweet.values 
#train_texts = [s.lower() for s in train_texts] 

#test_texts = test_df[1].values 
#test_texts = [s.lower() for s in test_texts] 

#=======================Convert string to index================
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences

# Tokenizer
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')
tk.fit_on_texts(train_texts)
# If we already have a character list, then replace the tk.word_index
# If not, just skip below part

#-----------------------Skip part start--------------------------
# construct a new vocabulary 
alphabet="abcdefghijklmnopqrstuvwxyz0123456789 ,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]{}"
char_dict = {}
for i, char in enumerate(alphabet):
    char_dict[char] = i + 1
    
# Use char_dict to replace the tk.word_index
tk.word_index = char_dict.copy() 
# Add 'UNK' to the vocabulary 
tk.word_index[tk.oov_token] = max(char_dict.values()) + 1
#-----------------------Skip part end----------------------------

# Convert string to index 
train_sequences = tk.texts_to_sequences(train_texts)
#test_texts = tk.texts_to_sequences(test_texts)

# Padding
train_data_tweets = pad_sequences(train_sequences, maxlen=1014, padding='post')
#test_data = pad_sequences(test_texts, maxlen=1014, padding='post')

# Convert to numpy array
train_data_tweets = np.array(train_data_tweets, dtype='float32')
#test_data = np.array(test_data, dtype='float32')

In [26]:
print(tk.word_index)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '0': 27, '1': 28, '2': 29, '3': 30, '4': 31, '5': 32, '6': 33, '7': 34, '8': 35, '9': 36, ' ': 37, ',': 38, ';': 39, '.': 40, '!': 41, '?': 42, ':': 43, "'": 44, '"': 45, '/': 46, '\\': 47, '|': 48, '_': 49, '@': 50, '#': 51, '$': 52, '%': 53, '^': 54, '&': 55, '*': 56, '~': 57, '`': 58, '+': 59, '-': 60, '=': 61, '<': 62, '>': 63, '(': 64, ')': 65, '[': 66, ']': 67, '{': 68, '}': 69, 'UNK': 70}


In [27]:
vocab_size = len(tk.word_index)
vocab_size

70

In [28]:
embedding_weights = [] #(71, 70)
embedding_weights.append(np.zeros(vocab_size)) # first row is pad

for char, i in tk.word_index.items(): # from index 1 to 70
    onehot = np.zeros(vocab_size)
    onehot[i-1] = 1
    embedding_weights.append(onehot)
embedding_weights = np.array(embedding_weights)

In [29]:
print(embedding_weights.shape) # first row all 0 for PAD, 69 char, last row for UNK
embedding_weights

(71, 70)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [30]:
from keras.layers import Input, Embedding, Activation, Flatten, Dense
from keras.layers import Conv1D, MaxPooling1D, Dropout
from keras.models import Model

In [31]:
# parameter 
input_size = 1014
#vocab_size = 69
embedding_size = 70
conv_layers = [[256, 7, 3], 
               [256, 7, 3], 
               [256, 3, -1], 
               [256, 3, -1], 
               [256, 3, -1], 
               [256, 3, 3]]

fully_connected_layers = [1024, 1024]
num_of_classes = 2
dropout_p = 0.5
optimizer = 'adam'
loss = tf.keras.losses.SparseCategoricalCrossentropy()

In [32]:
# Embedding layer Initialization
embedding_layer = Embedding(vocab_size+1, 
                            embedding_size,
                            input_length=input_size,
                            weights=[embedding_weights])

In [33]:
# Model 

# Input
inputs = Input(shape=(input_size,), name='input', dtype='int64')  # shape=(?, 1014)
# Embedding 
x = embedding_layer(inputs)
# Conv
for filter_num, filter_size, pooling_size in conv_layers:
    x = Conv1D(filter_num, filter_size)(x) 
    x = Activation('relu')(x)
    if pooling_size != -1:
        x = MaxPooling1D(pool_size=pooling_size)(x) # Final shape=(None, 34, 256)
x = Flatten()(x) # (None, 8704)
# Fully connected layers 
for dense_size in fully_connected_layers:
    x = Dense(dense_size, activation='relu')(x) # dense_size == 1024
    x = Dropout(dropout_p)(x)
# Output Layer
predictions = Dense(num_of_classes, activation='softmax')(x)
# Build model
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer=optimizer, metrics=['accuracy'],
              loss= loss) # Adam,
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 1014)]            0         
                                                                 
 embedding (Embedding)       (None, 1014, 70)          4970      
                                                                 
 conv1d (Conv1D)             (None, 1008, 256)         125696    
                                                                 
 activation (Activation)     (None, 1008, 256)         0         
                                                                 
 max_pooling1d (MaxPooling1D  (None, 336, 256)         0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 330, 256)          459008    
                                                             

In [34]:
train_label = train_data.loc[train_data_tweet.index]["target"]
train_label.value_counts()

4    80025
0    79975
Name: target, dtype: int64

In [35]:

train_label = train_label.astype('category')
train_label = train_label.cat.codes
train_label

250977    0
150064    0
710275    0
367641    0
575674    0
         ..
110202    0
777860    0
268962    0
983370    1
796007    0
Length: 160000, dtype: int8

In [36]:
type(train_label)

pandas.core.series.Series

In [37]:
train_label = train_label.to_numpy(dtype = int)
type(train_label)

numpy.ndarray

In [38]:
np.unique(train_label)

array([0, 1])

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train_data_tweets, train_label, test_size=0.20, random_state = 101)
X_train.shape, y_train.shape

((128000, 1014), (128000,))

In [41]:

history_1 = model.fit(  X_train, 
                        y_train,
                        epochs = 8,
                        batch_size = 256,
                        validation_data = (X_val, y_val)
                      )

Epoch 1/8
500/500 [==============================] - 95s 190ms/step - loss: 0.4812 - accuracy: 0.7730 - val_loss: 0.4810 - val_accuracy: 0.7708
Epoch 2/8
500/500 [==============================] - 94s 189ms/step - loss: 0.4331 - accuracy: 0.8011 - val_loss: 0.4865 - val_accuracy: 0.7703
Epoch 3/8
500/500 [==============================] - 97s 194ms/step - loss: 0.3926 - accuracy: 0.8243 - val_loss: 0.4855 - val_accuracy: 0.7808
Epoch 4/8
500/500 [==============================] - 97s 194ms/step - loss: 0.3451 - accuracy: 0.8490 - val_loss: 0.4868 - val_accuracy: 0.7786
Epoch 5/8
500/500 [==============================] - 97s 194ms/step - loss: 0.2877 - accuracy: 0.8787 - val_loss: 0.5455 - val_accuracy: 0.7686
Epoch 6/8
500/500 [==============================] - 97s 195ms/step - loss: 0.2324 - accuracy: 0.9057 - val_loss: 0.6273 - val_accuracy: 0.7604
Epoch 7/8
500/500 [==============================] - 97s 194ms/step - loss: 0.1838 - accuracy: 0.9266 - val_loss: 0.7276 - val_accuracy:

In [42]:
from sklearn.metrics import confusion_matrix

preds = np.argmax(model.predict(X_val), axis=1)
confusion_matrix(y_val, preds)

1000/1000 [==============================] - 9s 9ms/step


array([[11946,  3910],
       [ 3743, 12401]])

In [43]:
from sklearn.metrics import classification_report

target_names = ['negative', 'positive']
print(classification_report(y_val, preds, target_names=target_names))

              precision    recall  f1-score   support

    negative       0.76      0.75      0.76     15856
    positive       0.76      0.77      0.76     16144

    accuracy                           0.76     32000
   macro avg       0.76      0.76      0.76     32000
weighted avg       0.76      0.76      0.76     32000



## Validation on test dataset

In [44]:
test_index = list(set(train_data.index) - set(train_data_tweet.index))
test_data = train_data.loc[test_index].sample(frac = 0.1, random_state = 101)

In [46]:
test_data_tweet = test_data['text']
test_data_tweet = lower_case(test_data_tweet)
test_data_tweet = remove_url(test_data_tweet)
test_data_tweet = remove_userid(test_data_tweet)
test_data_tweet = remove_hastag(test_data_tweet)
test_data_tweet = character_clean(test_data_tweet)

In [47]:
test_texts = test_data_tweet.values
# Convert string to index 
test_sequences = tk.texts_to_sequences(test_texts)
#test_texts = tk.texts_to_sequences(test_texts)

# Padding
test_data_tweets = pad_sequences(test_sequences, maxlen=1014, padding='post')
#test_data = pad_sequences(test_texts, maxlen=1014, padding='post')

# Convert to numpy array
test_data_tweets = np.array(test_data_tweets, dtype='float32')
#test_data = np.array(test_data, dtype='float32')

In [48]:
test_label = train_data.loc[test_data_tweet.index]["target"]
print(test_label.value_counts())
test_label = test_label.astype('category')
test_label = test_label.cat.codes
test_label = test_label.to_numpy(dtype = int)

0    72032
4    71968
Name: target, dtype: int64


In [49]:
preds = np.argmax(model.predict(test_data_tweets), axis=1)
confusion_matrix(test_label, preds)

4500/4500 [==============================] - 39s 9ms/step


array([[54641, 17391],
       [16593, 55375]])

In [50]:
target_names = ['negative','positive']
print(classification_report(test_label, preds, target_names=target_names))

              precision    recall  f1-score   support

    negative       0.77      0.76      0.76     72032
    positive       0.76      0.77      0.77     71968

    accuracy                           0.76    144000
   macro avg       0.76      0.76      0.76    144000
weighted avg       0.76      0.76      0.76    144000

