In [ ]:
import pandas as pd
import sys
import re

In [ ]:
characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-,;.!?:'\"/\\|_@#$%^&*~`+ =<>()[]{}"
characters_2 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ@# "
url_chars = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"

In [ ]:
def lower_case(tweet):
    return tweet.lower()

In [ ]:
# def character_clean(tweet_data):
#     for i, tweet in enumerate(tweet_data):
#         sentence = ''
#         for char in tweet:
#             if char in characters_2:
#                 sentence += char
#         tweet_data.iloc[i] = sentence
#     return tweet_data

def character_clean(tweet):
    sentence = ''
    for char in tweet:
        if char in characters_2:
            sentence += char
    return sentence

In [ ]:
# def remove_hastag(tweet_data):
#     for i, tweet in enumerate(tweet_data):
#         ignore = 0
#         sentence = ''
#         for char in tweet:
#             if char == '#':
#                 ignore = 1
#             if ignore == 1 and char == ' ':
#                 ignore = 0
#             if ignore == 0:
#                 sentence += char
#         tweet_data.iloc[i] = sentence
#     return tweet_data

def remove_hastag(tweet):
    ignore = 0
    sentence = ''
    for char in tweet:
        if char == '#':
            ignore = 1
        if ignore == 1 and char == ' ':
            ignore = 0
        if ignore == 0:
            sentence += char
    return sentence

In [ ]:
# def remove_userid(tweet_data):
#     for i, tweet in enumerate(tweet_data):
#         ignore = 0
#         sentence = ''
#         for char in tweet:
#             if char == '@':
#                 ignore = 1
#             if ignore == 1 and char == ' ':
#                 ignore = 0
#             if ignore == 0:
#                 sentence += char
#         tweet_data.iloc[i] = sentence
#     return tweet_data

def remove_userid(tweet):
    ignore = 0
    sentence = ''
    for char in tweet:
        if char == '@':
            ignore = 1
        if ignore == 1 and char == ' ':
            ignore = 0
        if ignore == 0:
            sentence += char
    return sentence

In [ ]:
# def remove_url(tweet_data):
#     for i, tweet in enumerate(tweet_data):
#         url = re.findall(url_chars, tweet)
#         to_remove = [x[0] for x in url]
#         for _url in to_remove:
#             tweet = tweet.replace(_url, '')
#         sentence = tweet
#         tweet_data.iloc[i] = sentence
#     return tweet_data

def remove_url(tweet):
    url = re.findall(url_chars, tweet)
    to_remove = [x[0] for x in url]
    for _url in to_remove:
        tweet = tweet.replace(_url, '')
    return tweet

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
file = "/content/drive/MyDrive/Tweet/training.csv"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import chardet
with open(file, 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [ ]:
colnames = ["target","ids","date","flag","user","text"]

train_data = pd.read_csv(file,encoding='ISO-8859-1',names=colnames, header=None)

In [ ]:

train_data['target'].unique()

array([0, 4])

In [ ]:
train_data['target'].value_counts()

0    800000
4    800000
Name: target, dtype: int64

In [ ]:
train_data_tweet = train_data['text'].sample(frac = 1, random_state = 101)
train_data_tweet

250977     @Kardboard yea  ugh. I don't wanna move either...
150064     Guess there's a first time for everything, my ...
710275     My cousin is going to America and it's NOT FAI...
367641     @mitchelmusso Ahh this is my first comment to ...
575674     taking care of my good friend jessica she is s...
                                 ...                        
661055     @BrianJRussell http://twitpic.com/7r45l - OUCH...
204614     Have just seen the fittest guy ever ever ever ...
1525073                               Gotzzz my phone back! 
1263115    well I'm back, hair is washed, now it's all so...
1225567    @ErinSchmidt I love half naked chicks in water...
Name: text, Length: 1600000, dtype: object

## Preprocessing

In [ ]:
import numpy as np

In [ ]:
#train_data_tweet = pd.Series(np.vectorize(lower_case)(train_data_tweet),train_data_tweet.index)
#train_data_tweet

In [ ]:
train_data_tweet = pd.Series(np.vectorize(remove_url)(train_data_tweet),train_data_tweet.index)
train_data_tweet

250977     @Kardboard yea  ugh. I don't wanna move either...
150064     Guess there's a first time for everything, my ...
710275     My cousin is going to America and it's NOT FAI...
367641     @mitchelmusso Ahh this is my first comment to ...
575674     taking care of my good friend jessica she is s...
                                 ...                        
661055     @BrianJRussell  - OUCH!! it hurts me just to l...
204614     Have just seen the fittest guy ever ever ever ...
1525073                               Gotzzz my phone back! 
1263115    well I'm back, hair is washed, now it's all so...
1225567    @ErinSchmidt I love half naked chicks in water...
Length: 1600000, dtype: object

In [ ]:
train_data_tweet = pd.Series(np.vectorize(remove_userid)(train_data_tweet),train_data_tweet.index)
train_data_tweet

250977      yea  ugh. I don't wanna move either because a...
150064     Guess there's a first time for everything, my ...
710275     My cousin is going to America and it's NOT FAI...
367641      Ahh this is my first comment to youu!! Love i...
575674     taking care of my good friend jessica she is s...
                                 ...                        
661055             - OUCH!! it hurts me just to look at him 
204614     Have just seen the fittest guy ever ever ever ...
1525073                               Gotzzz my phone back! 
1263115    well I'm back, hair is washed, now it's all so...
1225567     I love half naked chicks in waterfalls! No id...
Length: 1600000, dtype: object

## Feature Extraction

In [ ]:

import nltk
nltk.download('words')
words = set(nltk.corpus.words.words())

[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


In [ ]:
def remove_nonEng(tweet):
    sentence = " ".join(w for w in nltk.wordpunct_tokenize(tweet) if w.lower() in words or not w.isalpha())
    return sentence

In [ ]:
import numpy as np

In [ ]:
#train_data_tweet = pd.Series(np.vectorize(remove_nonEng)(train_data_tweet),train_data_tweet.index)
#train_data_tweet

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# convert string to lower case 
train_texts = train_data_tweet.values 

#=======================Convert string to index================
from keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Tokenizer
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')
tk.fit_on_texts(train_texts)
# If we already have a character list, then replace the tk.word_index
# If not, just skip below part

#-----------------------Skip part start--------------------------
# construct a new vocabulary 
alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ,;.!?:'\"/\\|_@#$%^&*~`+-=<>()[]{}"
char_dict = {}
for i, char in enumerate(alphabet):
    char_dict[char] = i + 1
    
# Use char_dict to replace the tk.word_index
tk.word_index = char_dict.copy() 
# Add 'UNK' to the vocabulary 
tk.word_index[tk.oov_token] = max(char_dict.values()) + 1
#-----------------------Skip part end----------------------------

# Convert string to index 
train_sequences = tk.texts_to_sequences(train_texts)
#test_texts = tk.texts_to_sequences(test_texts)

# Padding
train_data_tweets = pad_sequences(train_sequences, maxlen=np.vectorize(len)(train_data["text"]).max(), padding='post')
#test_data = pad_sequences(test_texts, maxlen=1014, padding='post')

# Convert to numpy array
train_data_tweets = np.array(train_data_tweets, dtype='float32')
#test_data = np.array(test_data, dtype='float32')

In [ ]:
print(tk.word_index)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, 'A': 27, 'B': 28, 'C': 29, 'D': 30, 'E': 31, 'F': 32, 'G': 33, 'H': 34, 'I': 35, 'J': 36, 'K': 37, 'L': 38, 'M': 39, 'N': 40, 'O': 41, 'P': 42, 'Q': 43, 'R': 44, 'S': 45, 'T': 46, 'U': 47, 'V': 48, 'W': 49, 'X': 50, 'Y': 51, 'Z': 52, '0': 53, '1': 54, '2': 55, '3': 56, '4': 57, '5': 58, '6': 59, '7': 60, '8': 61, '9': 62, ' ': 63, ',': 64, ';': 65, '.': 66, '!': 67, '?': 68, ':': 69, "'": 70, '"': 71, '/': 72, '\\': 73, '|': 74, '_': 75, '@': 76, '#': 77, '$': 78, '%': 79, '^': 80, '&': 81, '*': 82, '~': 83, '`': 84, '+': 85, '-': 86, '=': 87, '<': 88, '>': 89, '(': 90, ')': 91, '[': 92, ']': 93, '{': 94, '}': 95, 'UNK': 96}


In [ ]:

vocab_size = len(tk.word_index)
vocab_size

96

In [ ]:
embedding_weights = [] #(71, 70)
embedding_weights.append(np.zeros(vocab_size)) # first row is pad

for char, i in tk.word_index.items(): # from index 1 to 70
    onehot = np.zeros(vocab_size)
    onehot[i-1] = 1
    embedding_weights.append(onehot)
embedding_weights = np.array(embedding_weights)

In [ ]:
print(embedding_weights.shape) # first row all 0 for PAD, 69 char, last row for UNK
embedding_weights

(97, 96)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
from keras.layers import Input, Embedding, Activation, Flatten, Dense
from keras.layers import Conv1D, MaxPooling1D, Dropout
from keras.models import Model

In [ ]:
# parameter 
input_size = np.vectorize(len)(train_data["text"]).max()
#vocab_size = 69
embedding_size = 96
conv_layers = [[256, 9, 3], 
               [256, 9, 3], 
               [256, 5, -1], 
               [256, 5, -1], 
               [256, 5, -1], 
               [256, 3, 3]]

fully_connected_layers = [1024, 1024]
num_of_classes = 2
dropout_p = 0.5
optimizer = 'adam'
loss = tf.keras.losses.SparseCategoricalCrossentropy()

In [ ]:
# Embedding layer Initialization
embedding_layer = Embedding(vocab_size+1, 
                            embedding_size,
                            input_length=input_size,
                            weights=[embedding_weights])

In [ ]:
# Model 

# Input
inputs = Input(shape=(input_size,), name='input', dtype='int16')  # shape=(?, 1014)
# Embedding 
x = embedding_layer(inputs)
# Conv
for filter_num, filter_size, pooling_size in conv_layers:
    x = Conv1D(filter_num, filter_size)(x) 
    x = Activation('relu')(x)
    if pooling_size != -1:
        x = MaxPooling1D(pool_size=pooling_size)(x) # Final shape=(None, 34, 256)
x = Flatten()(x) # (None, 8704)
# Fully connected layers 
for dense_size in fully_connected_layers:
    x = Dense(dense_size, activation='relu')(x) # dense_size == 1024
    x = Dropout(dropout_p)(x)
# Output Layer
predictions = Dense(num_of_classes, activation='softmax')(x)
# Build model
model = Model(inputs=inputs, outputs=predictions)
optim = tf.keras.optimizers.Adam(lr=0.02)
model.compile(optimizer=optim, metrics=['accuracy'],
              loss= loss) # Adam,
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input (InputLayer)          [(None, 374)]             0         
                                                                 
 embedding (Embedding)       (None, 374, 96)           9312      
                                                                 
 conv1d (Conv1D)             (None, 366, 256)          221440    
                                                                 
 activation (Activation)     (None, 366, 256)          0         
                                                                 
 max_pooling1d (MaxPooling1D  (None, 122, 256)         0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 114, 256)          590080    
                                                             

/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
train_label = train_data.loc[train_data_tweet.index]["target"]
train_label.value_counts()

0    800000
4    800000
Name: target, dtype: int64

In [ ]:

train_label = train_label.astype('category')
train_label = train_label.cat.codes
train_label

250977     0
150064     0
710275     0
367641     0
575674     0
          ..
661055     0
204614     0
1525073    1
1263115    1
1225567    1
Length: 1600000, dtype: int8

In [ ]:
type(train_label)

pandas.core.series.Series

In [ ]:
train_label = train_label.to_numpy(dtype = int)
type(train_label)

numpy.ndarray

In [ ]:
np.unique(train_label)

array([0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train_data_tweets, train_label, test_size=0.10, random_state = 101)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.10, random_state = 101)
X_train.shape, y_train.shape

((1296000, 374), (1296000,))

In [ ]:
checkpoint_filepath = '/content/checkpoint'
model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_filepath,
    save_weights_only=True,
    monitor='val_loss',
    mode='min',
    save_best_only=True)

In [ ]:

history_1 = model.fit(  np.array(X_train,np.float16), 
                        y_train,
                        #class_weight = {0: 1, 1:2},
                        epochs = 8,
                        batch_size = 1024,
                        validation_data = [np.array(X_val,np.float16),y_val],
                        callbacks = [model_checkpoint_callback]
                      )

Epoch 1/8
1266/1266 [==============================] - 414s 317ms/step - loss: 0.6692 - accuracy: 0.5759 - val_loss: 0.6233 - val_accuracy: 0.6533
Epoch 2/8
1266/1266 [==============================] - 402s 317ms/step - loss: 0.6034 - accuracy: 0.6741 - val_loss: 0.5870 - val_accuracy: 0.6892
Epoch 3/8
1266/1266 [==============================] - 402s 317ms/step - loss: 0.5715 - accuracy: 0.7031 - val_loss: 0.5603 - val_accuracy: 0.7108
Epoch 4/8
1266/1266 [==============================] - 402s 317ms/step - loss: 0.5492 - accuracy: 0.7206 - val_loss: 0.5433 - val_accuracy: 0.7243
Epoch 5/8
1266/1266 [==============================] - 401s 317ms/step - loss: 0.5334 - accuracy: 0.7324 - val_loss: 0.5310 - val_accuracy: 0.7330
Epoch 6/8
1266/1266 [==============================] - 402s 318ms/step - loss: 0.5212 - accuracy: 0.7415 - val_loss: 0.5239 - val_accuracy: 0.7384
Epoch 7/8
1266/1266 [==============================] - 402s 318ms/step - loss: 0.5120 - accuracy: 0.7477 - val_loss: 0

In [ ]:
model.load_weights(checkpoint_filepath)

In [ ]:
from sklearn.metrics import classification_report

preds = np.argmax(model.predict(X_val), axis=1)
target_names = ['negative',  'positive']
print(classification_report(y_val, preds, target_names=target_names))

4500/4500 [==============================] - 19s 4ms/step
              precision    recall  f1-score   support

    negative       0.74      0.77      0.75     71844
    positive       0.76      0.73      0.75     72156

    accuracy                           0.75    144000
   macro avg       0.75      0.75      0.75    144000
weighted avg       0.75      0.75      0.75    144000



In [ ]:
from sklearn.metrics import confusion_matrix

preds = np.argmax(model.predict(X_val), axis=1)
confusion_matrix(y_val, preds)

4500/4500 [==============================] - 19s 4ms/step


array([[55003, 16841],
       [19212, 52944]])

In [ ]:
target_names = ['negative',  'positive']
print(classification_report(y_val, preds, target_names=target_names))

              precision    recall  f1-score   support

    negative       0.74      0.77      0.75     71844
    positive       0.76      0.73      0.75     72156

    accuracy                           0.75    144000
   macro avg       0.75      0.75      0.75    144000
weighted avg       0.75      0.75      0.75    144000



## Validation on test dataset

In [ ]:
preds = np.argmax(model.predict(X_test), axis=1)
confusion_matrix(y_test, preds)

5000/5000 [==============================] - 21s 4ms/step


array([[61765, 18773],
       [21028, 58434]])

In [ ]:
target_names = ['negative','positive']
print(classification_report(y_test, preds, target_names=target_names))

              precision    recall  f1-score   support

    negative       0.75      0.77      0.76     80538
    positive       0.76      0.74      0.75     79462

    accuracy                           0.75    160000
   macro avg       0.75      0.75      0.75    160000
weighted avg       0.75      0.75      0.75    160000

